export const visitor_demo_data = [
  {
    icon: "https://flagcdn.com/w40/bd.png",
    country: "Bangladesh",
    region: "Dhaka",
    device: "Mobile",
    visited: "1 hr ago",
    visitCount: 1,
  },
  {
    icon: "https://flagcdn.com/w40/fi.png",
    country: "Finland",
    region: "Helsinki",
    device: "Mobile",
    visited: "yesterday",
    visitCount: 1,
  },
  {
    icon: "https://flagcdn.com/w40/pk.png",
    country: "Pakistan",
    region: "Korachi",
    device: "Mobile",
    visited: "1st May, 2025",
    visitCount: 1,
  },
  {
    icon: "https://flagcdn.com/w40/id.png",
    country: "Indonasia",
    region: "Maharashtra",
    device: "Desktop",
    visited: "1st May, 2025",
    visitCount: 1,
  },
  {
    icon: "https://flagcdn.com/w40/bd.png",
    country: "Bangladesh",
    region: "Dhaka",
    device: "Mobile",
    visited: "1st May, 2025",
    visitCount: 1,
  },
  {
    icon: "https://flagcdn.com/w40/nz.png",
    country: "Newziland",
    region: "Hockam",
    device: "Mobile",
    visited: "1st May, 2025",
    visitCount: 1,
  },
];
