export const WORK_EXPERIENCES = [
  {
    id: 1,
    timeline: "March 2024 - Present",
    position: "Software Engineer",
    company: "Echologyx Ltd.",
    companyColor: "text-orange-500",
    bgColor:
      "bg-gradient-to-br from-orange-50 to-amber-50 dark:from-orange-950/20 dark:to-amber-950/20",
    borderColor: "border-orange-200 dark:border-orange-800/30",
    iconBg: "bg-orange-100 dark:bg-orange-900/30",
    status: "Current Position",
    start_date: "2024-03-01",
    type: "Full-time",
    location: "Remote",
    technologies: [
      "React.js",
      "Node.js",
      "JavaScript",
      "Socket.IO",
      "Playwright",
      "Python",
      "OpenCV",
      "Django",
      "postgreSQL",
      "FastAPI",
      "Docker",
      "Resemble.js",
      "HTML Canvas",
      "WebSockets",
      "Sentence Transformers",
      "Vector DB",
      "Google ADK",
      "AI Chatbot",
      "A/B Testing",
      "Convert",
      "Google Optimize",
    ],
    achievements: [
      "Built a complete visual testing automation MVP using React, Node.js, and Python",
      "Implemented custom image diff engine with Resemble.js and Canvas API",
      "Developed a real-time browser automation system using Playwright and Socket.IO",
      "Integrated OpenCV for image analysis and visual diffing",
      "Worked in AI chatbot backend with Django and Docker",
      "Integrated vector database with semantic search via Sentence Transformers",
      "Explored Google ADK for a recommendation engine prototype",
      "Improved experiment-driven UX through A/B testing tools like Convert and Google Optimize",
    ],
    description: `<p>I began working with A/B testing after joining Echologyx, where I gained hands-on experience for around six months. Following that, I took on a solo project involving both frontend and backend development. This was an internal MVP for a visual testing automation tool designed to determine whether a live website's implementation matched its Figma design.</p>
<p>On the frontend, I used React along with Resemble.js to detect visual differences, and implemented a custom image mismatch mapping system using the HTML canvas. The backend was more complex, combining Node.js, Socket.IO, and Playwright for browser automation, along with Python and OpenCV for image comparison and processing. I also built a real-time browser control system that could open a webpage, scroll to specific sections, stream the view, and then capture targeted segments for visual comparison.</p>
<p>After completing that project, I shifted to another product development team where I joined in AI chatbot backend team. So I have started working with Python and Django. My work involved Django’s session management system, real-time communication with WebSockets, and containerization with Docker. Additionally, I explored vector databases for semantic search features, using Sentence Transformers, and experimented with Google ADK for building a product recommendation model.</p>`,
    highlights: [
      "A/B Testing Development",
      "AI Application Development",
      "Full-Stack Development",
    ],
  },
  {
    id: 2,
    timeline: "July 2023 - December 2023",
    position: "MERN Stack Developer",
    company: "Aykori Digital",
    companyColor: "text-green-500",
    bgColor:
      "bg-gradient-to-br from-green-50 to-emerald-50 dark:from-green-950/20 dark:to-emerald-950/20",
    borderColor: "border-green-200 dark:border-green-800/30",
    iconBg: "bg-green-100 dark:bg-green-900/30",
    status: "Completed",
    type: "Internship",
    start_date: "2023-07-22",
    end_date: "2023-12-31",
    location: "On-site",
    technologies: [
      "React JS",
      "Next JS",
      "Node JS",
      "Express",
      "MongoDB",
      "Tailwind CSS",
      "Redux",
      "Redux toolkit Query",
      "Material UI",
      "Google APIs"
    ],
    achievements: [
      "Redesigned and modernized legacy HRM interface using React and Tailwind",
      "Resolved backend bugs in the leave management module",
      "Built frontend modules for affiliates and campaign tracking in CMS",
      "Contributed full-stack features to a restaurant management CMS",
      "Gained practical experience working on multiple real-world production systems",
      "Collaborated with cross-functional teams to deliver updates on tight deadlines",
    ],
    description: `<p>I started my internship as a MERN stack developer at Aaykori, a fintech startup focused on affiliate and bonus systems for e-commerce platforms. In addition to the core product, the tech team also explored and developed several side projects.</p>
<p>During my time there, I initially contributed to an HRM (Human Resource Management) software, where I worked on converting the legacy UI into a modern design using frontend technologies. I also resolved backend bugs related to the leave management system, gaining hands-on experience with both client- and server-side debugging.</p>
<p>Later, I collaborated on the platform’s CMS system, particularly in the Affiliates and Campaigns sections, helping build dynamic interfaces and implementing logic for campaign tracking and user interactions. Toward the end of my internship, I worked on a Restaurant Management CMS, contributing to both the frontend and backend, which allowed me to strengthen my full-stack development skills in a production environment.</p>`,
    highlights: [
      "Full-Stack Development",
      "Fintech Industry Experience",
      "CMS & HRM Systems",
    ],
  },
];
